services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    working_dir: /var/www/html

    volumes:
      - .:/var/www/html
      - vendor:/var/www/html/vendor
      - node_modules:/var/www/html/node_modules
    
    ports:
      - "8000:8000"
    
    depends_on:
      - mysql
    
    command: php artisan serve --host=0.0.0.0 --port=8000
  
  vite:
    build:
      context: .
      dockerfile: Dockerfile.dev
    
    working_dir: /var/www/html

    volumes:
      - .:/var/www/html
      - node_modules:/var/www/html/node_modules
    
    ports:
      - "5173:5173"
    
    command: npm run dev -- --host 0.0.0.0

    depends_on:
      - app
    
  mysql:
    image: mysql:8.4

    environment:
      MYSQL_DATABASE: inkinspire
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: inkinspire
      MYSQL_PASSWORD: secret
    
    ports:
      - "3306:3306"
    
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data:
  vendor:
  node_modules: